[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = ["integration_test: marks tests as integration tests (deselect with '-m \"not integration_test\")"]

[tool.black]
line-length = 88
target-version = ["py39"]
include = ["qless", "qmore", "qless_test"]
exclude = ["README.md"]

[tool.isort]
include_trailing_comma = true
known_first_party = ["qless", "qmore", "qless_test"]
line_length = 88
lines_after_imports = 2
multi_line_output = 3
profile = "black"
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
skip_glob = ["qless/lua", "qless/qless-core"]
use_parentheses = true

[tool.mypy]
check_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
exclude = '^(qless/qless-core|qless/lua|fixtures|.*?\.js|.*?\.json)'
ignore_missing_imports = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true

[tool.pydantic-mypy]
init_forbid_extra = true
