[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.black]
exclude = "qless/qless-core/.*"
include = "(qless(_test)?|qmore)/.*\\.py$"
line-length = 88
target-version = ["py39"]

[tool.flake8]
exclude = ["qless/lua", "qless/qless-core"]
ignore = ["E203", "E251", "E701", "N805", "W503", "DAR101", "DAR201", "DAR301", "DAR401"]
max-line-length = 88
min_python_version = "3.9.0"

[tool.isort]
include_trailing_comma = true
known_first_party = ["qless", "qmore", "qless_test"]
line_length = 88
lines_after_imports = 2
multi_line_output = 3
profile = "black"
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
skip_glob = ["qless/lua", "qless/qless-core"]
use_parentheses = true

[tool.mypy]
check_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
exclude = "^(qless/qless-core|qless/lua|fixtures|.*?\\.js|.*?\\.json)"
ignore_missing_imports = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true

[tool.nosetests]
cover-branches = 1
cover-erase = 1
cover-min-percentage = 98
cover-package = ["qless", "qmore"]
exe = 1
logging-clear-handlers = 1
rednose = 1
verbosity = 2

[tool.pytest.ini_options]
markers = ["integration_test: marks tests as integration tests (deselect with '-m \"not integration_test\"')"]
